version : '3'
services :
  server :
    env_file:
      - .env
    build: 
      context: .
    image: ghcr.io/skeletonbear/back-end-punmaew:latest
    ports:
      - "5443:5443"
networks:
  default:
    external:
      name: punmaew

