version : '3'
services :
  restart: always
  server :
    env_file:
      - .env
    build: 
      context: .
    image: backend:latest
    ports:
      - "3000:3000"
      
networks:
  default:
    external:
      name: punmaew

